### ISSUE TITLE
Add slow end-point data to strong-pm mesh-models

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-mesh-models#12]
Add slow end-point data to strong-pm's loopback models in a manner similar to the ServiceMetrics: keeping only the last 5 minutes, having timerstamp, worker ID, process ID, and a json blob of the endpoint properties.

**Comment by chandadharap** [comment]
For reference: https://github.com/strongloop/strongops/pull/245

**Comment by cgole** [comment]
verified - 
Deployed loopback-example-app to strong-pm. 
See slow endpoints data with - 
http://localhost:7777/explorer/#!/AgentTraces/find

**Comment by rmg** [comment]
Released in strong-mesh-models@3.1.0
Will also be in @4.0.0 when it is released for strong-pm@2.0
