### ISSUE TITLE
analytics api backend not returning results

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-mesh-models#73]
I ran the load scripts against the `express-example-app` and got an empty array.

**Comment by sam-github** [comment]
api analytics are only returned if you use https://github.com/strongloop/strong-express-metrics

loopback does (I believe), or is intended to.

no other express app uses that middleware, at least not intentionally.

**Comment by bajtos** [comment]
> loopback does (I believe), or is intended to.

Not any more. We have reverted back the change adding strong-express-metrics to newly scaffolded apps, see https://github.com/strongloop/loopback-workspace/pull/201 for details.

Enabling API analytics is easy, just add `strong-express-metrics` middleware to your express app. If you are using loopback, then see https://github.com/strongloop/loopback-workspace/commit/6dc86830f5690bc247fbd6f3cbe9215479a29c80 for an example how to add the middleware to `server/middleware.json`.

**Comment by cgole** [comment]
@anthonyettinger, did you get a chance to try out what Sam said in his comment ?

**Comment by sam-github** [comment]
@anthonyettinger @cgole not a bug, this should be closed, or more info added
